BloodEffectEnabled: true # create blood when a player is hit
RespawnSoundEnabled: true # make eerie sound when player respawns/dies
RespawnEffectEnabled: true # give nausea to player on respawn/death

KeepInventoryEnabled: false # keep inventory?
KeepExperienceEnabled: false # keep experience?

LoseMaxHealthOnRespawnEnabled: true
LoseMaxHealthOnRespawnAmmount: 4.0 # 2.0 = 1 heart, 1.0 = half a heart
HealthLossText: "你感到你的力量流逝了许多"

BanOnDeathEnabled: false # ban on respawn/death?
BanOnDeathHoursAmmount: 12 # hours
BanOnDeathText: "你已被噩梦所环绕，永久的沉眠于此"

PermaBanOnFinalDeathEnabled: true # perma ban a player when they run out of max health?
PermaBanText: "你已被噩梦所环绕，永久的沉眠于此"

AnnounceDeathEnabled: true # announce when someone respawn/dies?
AnnounceDeathText: "%PLAYER% died." # <player> died.

PermaDeathServerText: " 没能再逃出噩梦..."
PermaDeathPlayerText: "你永久的沉眠于噩梦之中了..."

DragonKillRestoresMaxHealthEnabled: true # restore max health to all players in The End when dragon dies
DragonKillText: "你的噩梦结束了，传送门已开启，现在是时候离开这里了..."
MaxHealthRestoreText: "你的最大生命值上限已恢复."

# If BanOnDeath is enabled there's no reason to config below
# Without BanOnDeath, these give the immersion that the player woke from a bad dream instead of dying
RespawnBedText: "你从一场噩梦中醒来了..."
RespawnWildText: "没有栖息之所的你从噩梦中醒来了..."



# Totem fixed
TotemOfUndyingWorks: true # Disable or enable the Totem of Undying
TotemDeathPlayerText: "神秘的魔法力量拯救了你" # Text to display for the user when he/she uses a Totem of Undying


# Custom death messages
CustomDeathMessagesEnabled: true # Enable or disable custom death messages

# < dmsg > stands for Death Message

dmsg_BlockExplosion: "%PLAYER% 被炸飞了." # block explosions not tnt
dmsg_Contact: "%PLAYER% 被扎成了刺猬." # When player is touching a block like cactus
dmsg_Cramming: "%PLAYER% 被挤成了饼." # When a player is colliding with too many entities
dmsg_DragonBreath: "%PLAYER 被末影龙烤熟了." # Dragon Breathing fire
dmsg_Drowning: "%PLAYER% 被水淹没." # When player doesn't have enough oxygen
dmsg_EntityAttack: "%PLAYER% 被杀死了" # When player is killed by a melee attacked from another mob
dmsg_EntityExplosion: "%PLAYER% 被炸飞了." # TNT explosion
dmsg_Fall: "%PLAYER% 感受到了地心引力." # Fall damage
dmsg_FallingBlock: "%PLAYER% 被高空坠物击中." # When something like anvils falls on a player
dmsg_Fire: "%PLAYER% 玩火自焚." # Damage caused by direct exposure to fire
dmsg_FireTick: "%PLAYER% 引火上身." # Damage caused due to burns caused by fire
dmsg_FlyIntoWall: "%PLAYER% 与墙壁合为了一体." # When a player collides in a wall at high speeds
dmsg_HotFloor: "%PLAYER% 忘记了地板是岩浆做的." # When player is killed by magma blocks
dmsg_Lava: "%PLAYER% 切身体验了岩浆的味道." # When player is in lava
dmsg_Lightning: "%PLAYER% 渡劫失败" # When player is struck by lightning
dmsg_Magic: "%PLAYER% 被魔法杀死了." # Damage potion or a spell
dmsg_Poison: "%PLAYER% 的生命被汲取至尽." # Poison damage
dmsg_Projectile: "%PLAYER% 被射穿了." # When player is attacked by a projectile
dmsg_Starvation: "%PLAYER% 被饿死了" # When player runs out of food and dies
dmsg_Suffocation: "%PLAYER% 被方块卡住了." # When player is stuck in a wall
dmsg_Suicide: "%PLAYER% 自杀了." # When player is killed using the command "/kill"
dmsg_Thorns: "%PLAYER% 被荆棘致死了 ( •_•)" # The damage dealt by the Thorns enchantment
dmsg_Void: "%PLAYER% 被虚空吞噬." # When player dies in the void
dmsg_Wither: "%PLAYER% 凋零了." # When player dies to the wither effect
dmsg_Freeze: "%PLAYER% 被寒冷所冰封." # When player dies to the wither effect