name: HardcorePlus
version: 0.1.0
main: me.griimnak.hardcoreplus.HardcorePlus
api-version: 1.13
authors: [griimnak]
description: Enhances the vanilla Minecraft hardcore experience by degrading players' max health on death.
website: https://griimnak.me
commands:
  hardcoreplus:
    description: Plugin info.
    usage: /<command>
    alias: hcp
permissions:
  hardcoreplus.admin:
    description: Admin commands like setting max hp for players, etc.